version: '3.9'

services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres-db
    networks:
      - account-network

  postgres-db:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - account-network
    ports:
      - "${DB_PORT}:${DB_PORT}"

networks:
  account-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
