version: '3.9'

services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${SERVICE_DB_HOST}
      DB_PORT: ${SERVICE_DB_PORT}
      DB_USERNAME: ${SERVICE_DB_USERNAME}
      DB_PASSWORD: ${SERVICE_DB_PASSWORD}
      DB_NAME: ${SERVICE_DB_NAME}
    depends_on:
      - postgres-db
    networks:
      - account-network

  postgres-db:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: ${SERVICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${SERVICE_DB_NAME}
      DB_HOST: ${SERVICE_DB_HOST}
      DB_PORT: ${SERVICE_DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - account-network
    ports:
      - "${SERVICE_DB_PORT}:${SERVICE_DB_PORT}"

networks:
  account-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
